
http :
  listener:
    host: "0.0.0.0"
    port: "8082"
    path: "/fastGo/{serviceType}"
   
db:
  sql:
    host: "localhost"
    port: "3306"
    user: "root"
    password: "root123"
    dbName: "schedulenroutes"